name: Scheduled Data Pipeline

on:
  # 1. Allows you to run this manually from the "Actions" tab
  workflow_dispatch:
  
  # 2. Runs on a schedule
  schedule:
    # Runs "at minute 0 past every 3rd hour" (e.g., 00:00, 03:00, 06:00 UTC)
    - cron: '0 */6 * * *'

jobs:
  scrape-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Crawl4ai Setup
        run: |
          crawl4ai-setup

      - name: Run Scraper
        env:
          # Get the API key from your repo's secrets
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py
      
      - name: Run StarTech Scraper (startech_scraper.py)
        env:
          # Add Firecrawl key as a secret in repo settings
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }} 
        run: |
          python startech_scraper.py

      - name: Build Combined RAG Corpus
        run: |
          # Use the new combined script (create this file next)
          python build_combined_corpus.py
      
      # Pull the latest main branch
      - name: Pull latest changes from remote
        run: git pull origin main --rebase # Use rebase to avoid merge commits

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto: Update combined product corpus"
          # --- 👇 UPDATE FILE PATTERN ---
          file_pattern: "out/combined_corpus.* result/*/*.json startech_products.csv" 
          # --- 👆 ---
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
          # Add push options to handle potential force pushes cleanly
          push_options: '--force --force-with-lease'